# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-05 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cols',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='game',
            name='rows',
            field=models.IntegerField(default=8),
        ),
    ]
